apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-services
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - platform
  selector:
    matchLabels:
      monitoring: platform-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
