apiVersion: v1
kind: Service
metadata:
  labels:
  monitoring: platform-app
  name: orders
  namespace: platform
spec:
  selector:
    app: orders
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
